server:
  port: 7070

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:theRandomValueDb
    username: sa
    password:
  application:
    name: theRandomValue

api:
  key:
    recipe: ${RECIPE_API_KEY}